wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1730616710
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 13
      - 23
      - 61
      - 62
      4: 3.8.19
      5: 0.17.4
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
job_name:
  desc: null
  value: mind
gpt_emb_dim:
  desc: null
  value: 1536
gpt_emb_train_file:
  desc: null
  value: ../data/emb_mind
gpt_emb_validation_file:
  desc: null
  value: ../data/emb_mind
gpt_emb_test_file:
  desc: null
  value: ../data/emb_mind
train_file:
  desc: null
  value: ../data/train_news_cls.tsv
validation_file:
  desc: null
  value: ../data/test_news_cls.tsv
test_file:
  desc: null
  value: ../data/test_news_cls.tsv
max_length:
  desc: null
  value: 128
pad_to_max_length:
  desc: null
  value: false
model_name_or_path:
  desc: null
  value: bert-base-cased
use_slow_tokenizer:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 32
per_device_eval_batch_size:
  desc: null
  value: 8
weight_decay:
  desc: null
  value: 0.0
lr_scheduler_type:
  desc: null
  value: linear
output_dir:
  desc: null
  value: ../output
seed:
  desc: null
  value: 2022
checkpointing_steps:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
with_tracking:
  desc: null
  value: true
report_to:
  desc: null
  value: wandb
ignore_mismatched_sizes:
  desc: null
  value: false
trigger_seed:
  desc: null
  value: 2022
trigger_min_max_freq:
  desc: null
  value:
  - 0.005
  - 0.01
selected_trigger_num:
  desc: null
  value: 20
max_trigger_num:
  desc: null
  value: 4
word_count_file:
  desc: null
  value: ../data/word_countall.json
disable_pca_evaluate:
  desc: null
  value: false
disable_training:
  desc: null
  value: false
verify_dataset_size:
  desc: null
  value: 20
transform_hidden_size:
  desc: null
  value: 1536
transform_dropout_rate:
  desc: null
  value: 0.0
copy_learning_rate:
  desc: null
  value: 5.0e-05
copy_num_train_epochs:
  desc: null
  value: 75
copy_max_train_steps:
  desc: null
  value: null
copy_gradient_accumulation_steps:
  desc: null
  value: 1
copy_num_warmup_steps:
  desc: null
  value: 0
cls_hidden_dim:
  desc: null
  value: 256
cls_dropout_rate:
  desc: null
  value: 0.2
cls_learning_rate:
  desc: null
  value: 0.01
cls_num_train_epochs:
  desc: null
  value: 75
cls_max_train_steps:
  desc: null
  value: null
cls_gradient_accumulation_steps:
  desc: null
  value: 1
cls_num_warmup_steps:
  desc: null
  value: 0
data_name:
  desc: null
  value: mind
project_name:
  desc: null
  value: embmarker
use_copy_target:
  desc: null
  value: false
plot_sample_num:
  desc: null
  value: 600
vis_method:
  desc: null
  value: pca
watermark_num:
  desc: null
  value: 2
num_backdoored_samples:
  desc: null
  value: 3656
